#include "compiler.h"

#include <QByteArray>

#include "AnalysisError.h"
#include "LexicalError.h"
#include "Lexico.h"
#include "Semantico.h"
#include "SemanticError.h"
#include "Sintatico.h"
#include "SyntacticError.h"
#include "Token.h"

namespace {

// GALS reports every error as a byte offset inside the source it was given.
// The editor needs a 1-based line/column pair instead.
void offsetToLineColumn(const QByteArray &utf8, int offset, int *line, int *column)
{
    *line = 1;
    *column = 1;

    if (offset < 0)
        return;

    const int limit = qMin(offset, utf8.size());
    int lineStart = 0;

    for (int i = 0; i < limit; ++i) {
        if (utf8.at(i) == '\n') {
            ++(*line);
            lineStart = i + 1;
        }
    }

    // Count characters, not bytes, so accents in the source do not shift the column.
    *column = QString::fromUtf8(utf8.mid(lineStart, limit - lineStart)).size() + 1;
}

// Runs the scanner once at `offset` to recover the lexeme the parser rejected.
// The parser only hands us a position, and "unexpected '<lexeme>'" is far more
// useful than the generic "Erro estado N" of PARSER_ERROR.
QString lexemeAt(const QByteArray &utf8, int offset)
{
    if (offset < 0 || offset >= utf8.size())
        return QString();

    Lexico scanner(utf8.constData());
    scanner.setPosition(static_cast<unsigned>(offset));

    try {
        Token *token = scanner.nextToken();
        if (token == nullptr)
            return QString();

        const QString lexeme = QString::fromStdString(token->getLexeme());
        delete token;
        return lexeme;
    } catch (const AnalysisError &) {
        return QString();
    }
}

// Second pass over an already valid source, only to report how much was read.
int countTokens(const QByteArray &utf8)
{
    Lexico scanner(utf8.constData());
    int total = 0;

    try {
        while (Token *token = scanner.nextToken()) {
            delete token;
            ++total;
        }
    } catch (const AnalysisError &) {
        // Cannot happen: the parser already consumed the whole input.
    }

    return total;
}

CompileResult failure(const QByteArray &utf8, const QString &message, int offset)
{
    CompileResult result;
    result.success = false;
    result.message = message;
    offsetToLineColumn(utf8, offset, &result.line, &result.column);
    return result;
}

} // namespace

namespace Compiler {

// ---------------------------------------------------------------------------
// Drives the analyser generated by GALS (see grammar/compiler.gals) and turns
// its exceptions into the line/column pair the editor highlights.
// ---------------------------------------------------------------------------
CompileResult analyze(const QString &source)
{
    const QByteArray utf8 = source.toUtf8();

    Lexico scanner(utf8.constData());
    Semantico semanticAnalyser;
    Sintatico parser;

    try {
        parser.parse(&scanner, &semanticAnalyser);
    } catch (const LexicalError &error) {
        return failure(utf8,
                       QString("Lexical error: %1.").arg(QString::fromUtf8(error.getMessage())),
                       error.getPosition());
    } catch (const SyntacticError &error) {
        const QString lexeme = lexemeAt(utf8, error.getPosition());
        const QString message = lexeme.isEmpty()
                                    ? QString("Syntax error: unexpected end of file.")
                                    : QString("Syntax error: unexpected '%1'.").arg(lexeme);
        return failure(utf8, message, error.getPosition());
    } catch (const SemanticError &error) {
        return failure(utf8,
                       QString("Semantic error: %1.").arg(QString::fromUtf8(error.getMessage())),
                       error.getPosition());
    } catch (const AnalysisError &error) {
        return failure(utf8, QString::fromUtf8(error.getMessage()), error.getPosition());
    }

    CompileResult result;
    result.success = true;
    result.message = QString("Program compiled successfully.\n"
                             "%1 line(s), %2 token(s) analyzed.")
                         .arg(source.count('\n') + 1)
                         .arg(countTokens(utf8));
    return result;
}

} // namespace Compiler
